version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP server

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9002:9000" # S3-compatible API
      - "9003:9001" # MinIO Console
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  redis_data:
  portainer_data:
  minio_data:
